### ISSUE TITLE
Add support for DNS forwarded zones

### ISSUE THREAD

**Issue by jbfarez** [bernadinm/tf_dcos_core#14]
Purpose
--
It's just about implementing the ability to use the [forwarded zones](https://docs.mesosphere.com/1.10/installing/custom/configuration/configuration-parameters/#dns_forward_zones) into the template config.

Will try to implement it ASAP and make a PR.

**Comment by bernadinm** [comment]
Thank you @jbfarez. I will be looking to add this feature in the near future as well. Thank you for reporting this. I will close out this case once when I provide the flag.

**Comment by jbfarez** [comment]
Hey @bernadinm, actually I've made a [relative PR](https://github.com/bernadinm/tf_dcos_core/pull/15) to move faster, you just have to review it 😉. Feel free to comment it, I can do some modifications if required.

**Comment by bernadinm** [comment]
ty @jbfarez! I have successfully merged your changes. Thanks for your help! 👍
